slug: aswf
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
landscapeMemberCategory: ASWF Member Company
landscapefile: landscape.yml
missingcsvfile: missing.csv
landscapeProjectsCategory: ASWF Projects
landscapeProjectsSubcategories:
  - name: All
    category: All
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/academy-software-foundation
