landscapeName: aswf
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
project: a09410000182dD2AAI # Academy Software Foundation
landscapeMemberCategory: ASWF Member Company
landscapefile: landscape.yml
missingcsvfile: missing.csv
