[build]
  base = "netlify"
  publish = "dist"
  command = "(wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/75-weekly-2020-05-30/netlify/landscape.js || wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/master/netlify/landscape.js) && node landscape.js"
  ignore = "false"
  environment = { RUBY_VERSION = "2.6.2", NODE_VERSION="14.3" }


