global:
  name: ASWF Interactive Landscape
  short_name: ASWF
  repo: AcademySoftwareFoundation/aswf-landscape
  website: https://landscape.aswf.io
  short_domain: l.aswf.io
  company_url: https://aswf.io
  email: info@aswf.io
  self: https://www.crunchbase.com/organization/academy-software-foundation
  slack_channel: T08PSQ7BQ/BM3K5125V/VfQL9ybcXrwpnLAdKdU8WQrr
  meta:
    title: ASWF Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@AcademySwf'
    google_site_verification: crYr16dyu7npMmK-fw42gMkXKTWg_A-7c2PosXgtPZo
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
    extra: |
      <!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=360578303"></script> <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '360578303');
      </script>
  membership: ASWF Member Company
  flags:
    companies: ASWF Member Company
twitter:
  search: landscape.aswf.io
  url: https://landscape.aswf.io
  text: ASWF Landscape from @AcademySwf
relation:
  label: ASWF Relation
  url: aswf
  values:
    - id: hosted
      label: ASWF Projects
      children:
        - id: adopted
          label: Adopted Projects
          prefix: ASWF
          tag: Adopted
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: ASWF Adopted
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubation Projects
          prefix: ASWF
          tag: Incubation
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: ASWF Incubation
          big_picture_color: rgb(83, 113, 189)
        - id: sandbox
          label: Sandbox Projects
          prefix: ASWF
          tag: Sandbox
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: ASWF Sandbox
          big_picture_color: rgb(108, 165, 209)
        - id: working-group
          label: Working Groups
          prefix: ASWF
          tag: Working Group
          color: '#666666'
          big_picture_order: 2
          big_picture_label: ASWF Working Group
          big_picture_color: rgb(200,200,200)
    - id: company
      label: ASWF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: ASWF Member Products/Projects
      tag: ASWF Member
    - id: false
      label: Non-ASWF Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: ASWF
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: ASWF
    label: General Member
    funding: General
  Associate:
    name: ASWF
    label: Associate Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>ASWF Interactive Landscape</h1> The Academy Software Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/open-source-days/?utm_source=aswf_landscape&utm_medium=web&utm_campaign=aswfosd2023
    image: /images/info1.jpg
    title: ASWF Open Source Days 2023
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: OS cards by age
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=license&license=open-source
    label: Group by license
  - url: /format=card-mode&grouping=no&license=open-source&sort=latest-commit
    label: OS cards by latest commit
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Academy Software Foundation Landscape
    fullscreen_header: See the interactive landscape at l.aswf.io
    elements:
      - type: HorizontalCategory
        category: Imaging and Color
        rows: 3
        width: 750
        height: 170
        top: 10
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: false
      - type: HorizontalCategory
        category: Assets and Workflow
        rows: 3
        width: 750
        height: 170
        top: 220
        left: 0
        color: rgb(19,105,73)
        fit_width: true
        is_large: false
      - type: HorizontalCategory
        category: Rendering and Queueing
        rows: 4
        width: 365
        height: 200
        top: 420
        left: 0
        color: rgb(47,116,190)
        fit_width: true
        is_large: false
      - type: HorizontalCategory
        category: Math and Simulation
        rows: 4
        width: 365
        height: 200
        top: 420
        left: 385
        color: rgb(165,9,77)
        fit_width: true
        is_large: false
      - type: VerticalCategory
        category: ASWF Member Company
        cols: 8
        width: 380
        height: 464
        top: 156
        left: 765
        color: rgb(193,83,21)
        fit_width: true
        is_large: false
      - type: LandscapeInfo
        width: 380
        height: 130
        top: 10
        left: 765
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source projects within the animation and visual effects industry, and also shows the member
              companies of the Academy Software Foundation.
            top: 10
            left: 85
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 4
            left: 1
            width: 88
            height: 90
            title: QR Code
          - type: title
            title: l.aswf.io
            top: 84
            left: 24
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 65
            title: ASWF Logo
test:
  header: ASWF Interactive Landscape
  section: Adopted Projects
  logo: open-vdb.svg
prerender:
  members: /card-mode?style=borderless&category=aswf-member-company&grouping=category&embed=yes
  hosted-projects: /card-mode?embed=yes&project=hosted&style=borderless
  hosted-projects-active: /card-mode?embed=yes&project=graduated&style=borderless
  hosted-projects-incubating: /card-mode?embed=yes&project=incubating&style=borderless
  working-groups: /card-mode?embed=yes&project=working-group&style=borderless
  dev-days-2024: /card-mode?category=participating-project&grouping=category&embed=yes&style=borderless
export:
  projects-hosted: card-mode?grouping=no&project=hosted
  projects-hosted-by-stage: card-mode?project=hosted
