name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: jmertic/lfx-landscape-tools@main
        env:
          token: ${{ secrets.PAT }}
          ghid_token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
